import os

with open('translations.js', 'r', encoding='utf-8') as f:
    js = f.read()

additions = {
    "'tr': {": """        'mega.turkiye': 'Türkiye',
        'mega.temel_fatura': 'TEMELFATURA',
        'mega.ticari_fatura': 'TİCARİFATURA',
        'mega.satis': 'SATIŞ',
        'mega.iade': 'İADE',
        'word.adet': 'Adet',
        'word.kg': 'Kg',
        'word.ton': 'Ton',
        'word.container': 'Konteyner',
        'word.carton': 'Karton',
        'word.box': 'Kutu',
        'word.net_ton': 'Net Ton',
        'word.gross_ton': 'Brüt Ton',
        'mega.kdv_haric': 'Kdv Hariç',
        'mega.otv_dahil': 'Ötv Dahil',
        'mega.otv_haric': 'Ötv Hariç',
        'word.yuzde': 'Yüzde',
        'word.tutar': 'Tutar',
        'word.yok': 'Yok',
        'word.seciniz': 'Seçiniz...',
        'mega.genel_aciklama': 'Genel Açıklama',
        'mega.odeme_notu': 'Ödeme Notu',
        'mega.teslimat_notu': 'Teslimat Notu',
        'mega.merkez': 'Merkez',
        'mega.sube_1': 'Şube 1',
        'mega.sube_kasa': 'Şube Kasa',
        'word.nakit': 'Nakit',
        'mega.kredi_karti': 'Kredi Kartı',
        'mega.havale_eft': 'Havale/EFT',
        'word.cek': 'Çek',
        'word.senet': 'Senet',
        'mega.kasa_seciniz': 'Kasa Seçiniz',
""",
    "'en': {": """        'mega.turkiye': 'Turkey',
        'mega.temel_fatura': 'BASIC INVOICE',
        'mega.ticari_fatura': 'COMMERCIAL',
        'mega.satis': 'SALE',
        'mega.iade': 'RETURN',
        'word.adet': 'Piece',
        'word.kg': 'Kg',
        'word.ton': 'Ton',
        'word.container': 'Container',
        'word.carton': 'Carton',
        'word.box': 'Box',
        'word.net_ton': 'Net Ton',
        'word.gross_ton': 'Gross Ton',
        'mega.kdv_haric': 'VAT Excluded',
        'mega.otv_dahil': 'SCT Included',
        'mega.otv_haric': 'SCT Excluded',
        'word.yuzde': 'Percentage',
        'word.tutar': 'Amount',
        'word.yok': 'None',
        'word.seciniz': 'Select...',
        'mega.genel_aciklama': 'General Description',
        'mega.odeme_notu': 'Payment Note',
        'mega.teslimat_notu': 'Delivery Note',
        'mega.merkez': 'Center',
        'mega.sube_1': 'Branch 1',
        'mega.sube_kasa': 'Branch Cash',
        'word.nakit': 'Cash',
        'mega.kredi_karti': 'Credit Card',
        'mega.havale_eft': 'Wire/EFT',
        'word.cek': 'Check',
        'word.senet': 'Promissory Note',
        'mega.kasa_seciniz': 'Select Cash',
""",
    "'de': {": """        'mega.turkiye': 'Türkei',
        'mega.temel_fatura': 'BASISRECHNUNG',
        'mega.ticari_fatura': 'GEWERBLICH',
        'mega.satis': 'VERKAUF',
        'mega.iade': 'RÜCKGABE',
        'word.adet': 'Stück',
        'word.kg': 'Kg',
        'word.ton': 'Tonne',
        'word.container': 'Container',
        'word.carton': 'Karton',
        'word.box': 'Box',
        'word.net_ton': 'Netto Tonne',
        'word.gross_ton': 'Brutto Tonne',
        'mega.kdv_haric': 'Ohne MwSt',
        'mega.otv_dahil': 'Inkl. ÖTV',
        'mega.otv_haric': 'Ohne ÖTV',
        'word.yuzde': 'Prozent',
        'word.tutar': 'Betrag',
        'word.yok': 'Keine',
        'word.seciniz': 'Auswählen...',
        'mega.genel_aciklama': 'Allgemeine Beschreibung',
        'mega.odeme_notu': 'Zahlungsnotiz',
        'mega.teslimat_notu': 'Liefernotiz',
        'mega.merkez': 'Zentrum',
        'mega.sube_1': 'Filiale 1',
        'mega.sube_kasa': 'Filialkasse',
        'word.nakit': 'Bar',
        'mega.kredi_karti': 'Kreditkarte',
        'mega.havale_eft': 'Überweisung/EFT',
        'word.cek': 'Scheck',
        'word.senet': 'Schuldschein',
        'mega.kasa_seciniz': 'Kasse Auswählen',
""",
    "'ru': {": """        'mega.turkiye': 'Турция',
        'mega.temel_fatura': 'БАЗОВЫЙ СЧЕТ',
        'mega.ticari_fatura': 'КОММЕРЧЕСКИЙ',
        'mega.satis': 'ПРОДАЖА',
        'mega.iade': 'ВОЗВРАТ',
        'word.adet': 'Штука',
        'word.kg': 'Кг',
        'word.ton': 'Тонна',
        'word.container': 'Контейнер',
        'word.carton': 'Картон',
        'word.box': 'Коробка',
        'word.net_ton': 'Нетто-тонна',
        'word.gross_ton': 'Брутто-тонна',
        'mega.kdv_haric': 'Без НДС',
        'mega.otv_dahil': 'Вкл. ОН',
        'mega.otv_haric': 'Без ОН',
        'word.yuzde': 'Процент',
        'word.tutar': 'Сумма',
        'word.yok': 'Нет',
        'word.seciniz': 'Выберите...',
        'mega.genel_aciklama': 'Общее описание',
        'mega.odeme_notu': 'Примечание к оплате',
        'mega.teslimat_notu': 'Примечание к доставке',
        'mega.merkez': 'Центр',
        'mega.sube_1': 'Филиал 1',
        'mega.sube_kasa': 'Касса филиала',
        'word.nakit': 'Наличные',
        'mega.kredi_karti': 'Кредитная карта',
        'mega.havale_eft': 'Перевод/ЭФТ',
        'word.cek': 'Чек',
        'word.senet': 'Вексель',
        'mega.kasa_seciniz': 'Выберите кассу',
""",
    "'zh': {": """        'mega.turkiye': '土耳其',
        'mega.temel_fatura': '基本发票',
        'mega.ticari_fatura': '商业发票',
        'mega.satis': '销售',
        'mega.iade': '退货',
        'word.adet': '件',
        'word.kg': '公斤',
        'word.ton': '吨',
        'word.container': '集装箱',
        'word.carton': '纸箱',
        'word.box': '盒子',
        'word.net_ton': '净吨',
        'word.gross_ton': '毛吨',
        'mega.kdv_haric': '不含增值税',
        'mega.otv_dahil': '含特别消费税',
        'mega.otv_haric': '不含特别消费税',
        'word.yuzde': '百分比',
        'word.tutar': '金额',
        'word.yok': '无',
        'word.seciniz': '请选择...',
        'mega.genel_aciklama': '一般描述',
        'mega.odeme_notu': '付款备注',
        'mega.teslimat_notu': '交货备注',
        'mega.merkez': '中心',
        'mega.sube_1': '分店 1',
        'mega.sube_kasa': '分店现金',
        'word.nakit': '现金',
        'mega.kredi_karti': '信用卡',
        'mega.havale_eft': '汇款/电子资金转账',
        'word.cek': '支票',
        'word.senet': '本票',
        'mega.kasa_seciniz': '选择现金',
"""
}

if "'mega.turkiye'" not in js:
    for target, extra in additions.items():
        js = js.replace(target, target + "\n" + extra)
    
    with open('translations.js', 'w', encoding='utf-8') as f:
        f.write(js)
    print("Injected into translations.js")
else:
    print("Already in translations.js")

