import os

with open('translations.js', 'r', encoding='utf-8') as f:
    js = f.read()

additions = {
    "'tr': {": """        'sidebar.sales_invoice': 'Satış Faturası',
        'word.eposta': 'E-posta',
        'mega.vergi_dairesi': 'Vergi Dairesi',
        'word.il': 'İl',
        'word.ilce': 'İlçe',
        'word.ulke': 'Ülke',
        'mega.detay_bilgiler': 'Detay Bilgiler',
        'mega.fatura_tarihi': 'Fatura Tarihi',
        'mega.vade_tarihi': 'Vade Tarihi',
        'mega.fatura_no': 'Fatura No',
        'mega.kdv_dahil': 'KDV Dahil',
        'mega.para_birimleri': 'Para Birimleri',
        'mega.doviz_kuru': 'Döviz Kuru',
        'mega.barkod': 'Barkod...',
        'mega.urun_ekle': 'Ürün Ekle',
        'word.birim_fiyati': 'Birim Fiyatı',
        'word.miktar': 'Miktar',
        'word.toplam': 'Toplam',
        'word.isk_percent': 'İsk %',
        'word.isk': 'İsk',
        'word.g_toplam': 'Genel Toplam',
        'word.islemler': 'İşlemler',
        'mega.tutarlar': 'Tutarlar',
        'mega.toplu_iskonto': 'Toplu İskonto',
        'word.iskonto': 'İskonto',
        'word.ara_toplam': 'Ara Toplam',
        'mega.kdv_tutar': 'KDV Tutar',
        'mega.otv_tutar': 'ÖTV Tutar',
        'mega.diger_vergiler': 'Diğer Vergiler',
        'mega.tevkifat': 'Tevkifat',
        'mega.oran': 'Oran',
        'mega.aciklama_basligi': 'Açıklama Başlığı',
        'mega.aciklamalar': 'Açıklamalar',
        'mega.aciklama': 'Açıklama',
        'mega.aciklama_kaydet': 'Açıklama Kaydet',
        'mega.odenen': 'Ödenen',
        'mega.depo_seciniz': 'Depo Seçiniz',
        'mega.merkez_kasa': 'Merkez Kasa / Şube Kasa',
        'mega.odeme_sekli': 'Ödeme Şekli',
""",
    "'en': {": """        'sidebar.sales_invoice': 'Sales Invoice',
        'word.eposta': 'Email',
        'mega.vergi_dairesi': 'Tax Office',
        'word.il': 'City',
        'word.ilce': 'District',
        'word.ulke': 'Country',
        'mega.detay_bilgiler': 'Details',
        'mega.fatura_tarihi': 'Invoice Date',
        'mega.vade_tarihi': 'Due Date',
        'mega.fatura_no': 'Invoice No',
        'mega.kdv_dahil': 'VAT Included',
        'mega.para_birimleri': 'Currency',
        'mega.doviz_kuru': 'Exchange Rate',
        'mega.barkod': 'Barcode...',
        'mega.urun_ekle': 'Add Product',
        'word.birim_fiyati': 'Unit Price',
        'word.miktar': 'Quantity',
        'word.toplam': 'Total',
        'word.isk_percent': 'Disc %',
        'word.isk': 'Discount',
        'word.g_toplam': 'Grand Total',
        'word.islemler': 'Actions',
        'mega.tutarlar': 'Amounts',
        'mega.toplu_iskonto': 'Bulk Discount',
        'word.iskonto': 'Discount',
        'word.ara_toplam': 'Subtotal',
        'mega.kdv_tutar': 'VAT Amount',
        'mega.otv_tutar': 'SCT Amount',
        'mega.diger_vergiler': 'Other Taxes',
        'mega.tevkifat': 'Withholding',
        'mega.oran': 'Rate',
        'mega.aciklama_basligi': 'Description Title',
        'mega.aciklamalar': 'Descriptions',
        'mega.aciklama': 'Description',
        'mega.aciklama_kaydet': 'Save Description',
        'mega.odenen': 'Paid',
        'mega.depo_seciniz': 'Select Warehouse',
        'mega.merkez_kasa': 'Head / Branch Cash',
        'mega.odeme_sekli': 'Payment Method',
""",
    "'de': {": """        'sidebar.sales_invoice': 'Verkaufsrechnung',
        'word.eposta': 'E-Mail',
        'mega.vergi_dairesi': 'Finanzamt',
        'word.il': 'Stadt',
        'word.ilce': 'Bezirk',
        'word.ulke': 'Land',
        'mega.detay_bilgiler': 'Details',
        'mega.fatura_tarihi': 'Rechnungsdatum',
        'mega.vade_tarihi': 'Fälligkeitsdatum',
        'mega.fatura_no': 'Rechnungsnummer',
        'mega.kdv_dahil': 'Inkl. MwSt',
        'mega.para_birimleri': 'Währungen',
        'mega.doviz_kuru': 'Wechselkurs',
        'mega.barkod': 'Barcode...',
        'mega.urun_ekle': 'Produkt Hinzufügen',
        'word.birim_fiyati': 'Einzelpreis',
        'word.miktar': 'Menge',
        'word.toplam': 'Gesamt',
        'word.isk_percent': 'Rabatt %',
        'word.isk': 'Rabatt',
        'word.g_toplam': 'Gesamtsumme',
        'word.islemler': 'Aktionen',
        'mega.tutarlar': 'Beträge',
        'mega.toplu_iskonto': 'Mengenrabatt',
        'word.iskonto': 'Rabatt',
        'word.ara_toplam': 'Zwischensumme',
        'mega.kdv_tutar': 'MwSt-Betrag',
        'mega.otv_tutar': 'ÖTV-Betrag',
        'mega.diger_vergiler': 'Andere Steuern',
        'mega.tevkifat': 'Quellensteuer',
        'mega.oran': 'Rate',
        'mega.aciklama_basligi': 'Titel',
        'mega.aciklamalar': 'Beschreibungen',
        'mega.aciklama': 'Beschreibung',
        'mega.aciklama_kaydet': 'Beschreibung Speichern',
        'mega.odenen': 'Bezahlt',
        'mega.depo_seciniz': 'Lager Auswählen',
        'mega.merkez_kasa': 'Haupt-/Zweigkasse',
        'mega.odeme_sekli': 'Zahlungsmethode',
""",
    "'ru': {": """        'sidebar.sales_invoice': 'Счет-фактура на продажу',
        'word.eposta': 'Email',
        'mega.vergi_dairesi': 'Налоговая инспекция',
        'word.il': 'Город',
        'word.ilce': 'Район',
        'word.ulke': 'Страна',
        'mega.detay_bilgiler': 'Детали',
        'mega.fatura_tarihi': 'Дата счета',
        'mega.vade_tarihi': 'Срок оплаты',
        'mega.fatura_no': 'Номер счета',
        'mega.kdv_dahil': 'Вкл. НДС',
        'mega.para_birimleri': 'Валюты',
        'mega.doviz_kuru': 'Курс валюты',
        'mega.barkod': 'Штрих-код...',
        'mega.urun_ekle': 'Добавить продукт',
        'word.birim_fiyati': 'Цена за единицу',
        'word.miktar': 'Количество',
        'word.toplam': 'Итого',
        'word.isk_percent': 'Скидка %',
        'word.isk': 'Скидка',
        'word.g_toplam': 'Общий итог',
        'word.islemler': 'Действия',
        'mega.tutarlar': 'Суммы',
        'mega.toplu_iskonto': 'Оптовая скидка',
        'word.iskonto': 'Скидка',
        'word.ara_toplam': 'Подытог',
        'mega.kdv_tutar': 'Сумма НДС',
        'mega.otv_tutar': 'Сумма ОН',
        'mega.diger_vergiler': 'Другие налоги',
        'mega.tevkifat': 'Удержание',
        'mega.oran': 'Ставка',
        'mega.aciklama_basligi': 'Заголовок описания',
        'mega.aciklamalar': 'Описания',
        'mega.aciklama': 'Описание',
        'mega.aciklama_kaydet': 'Сохранить описание',
        'mega.odenen': 'Оплачено',
        'mega.depo_seciniz': 'Выберите склад',
        'mega.merkez_kasa': 'Главная / Филиал касса',
        'mega.odeme_sekli': 'Способ оплаты',
""",
    "'zh': {": """        'sidebar.sales_invoice': '销售发票',
        'word.eposta': '电子邮件',
        'mega.vergi_dairesi': '税务局',
        'word.il': '城市',
        'word.ilce': '区',
        'word.ulke': '国家',
        'mega.detay_bilgiler': '详情',
        'mega.fatura_tarihi': '发票日期',
        'mega.vade_tarihi': '到期日期',
        'mega.fatura_no': '发票号码',
        'mega.kdv_dahil': '含增值税',
        'mega.para_birimleri': '货币',
        'mega.doviz_kuru': '汇率',
        'mega.barkod': '条形码...',
        'mega.urun_ekle': '添加产品',
        'word.birim_fiyati': '单价',
        'word.miktar': '数量',
        'word.toplam': '总计',
        'word.isk_percent': '折扣 %',
        'word.isk': '折扣',
        'word.g_toplam': '总计',
        'word.islemler': '操作',
        'mega.tutarlar': '金额',
        'mega.toplu_iskonto': '批量折扣',
        'word.iskonto': '折扣',
        'word.ara_toplam': '小计',
        'mega.kdv_tutar': '增值税额',
        'mega.otv_tutar': '特别消费税',
        'mega.diger_vergiler': '其他税',
        'mega.tevkifat': '预扣税',
        'mega.oran': '税率',
        'mega.aciklama_basligi': '描述标题',
        'mega.aciklamalar': '描述',
        'mega.aciklama': '描述',
        'mega.aciklama_kaydet': '保存描述',
        'mega.odenen': '已支付',
        'mega.depo_seciniz': '选择仓库',
        'mega.merkez_kasa': '总/分部现金',
        'mega.odeme_sekli': '付款方式',
"""
}

if "'sidebar.sales_invoice'" not in js:
    for target, extra in additions.items():
        js = js.replace(target, target + "\n" + extra)
    
    with open('translations.js', 'w', encoding='utf-8') as f:
        f.write(js)
    print("Injected bulk words into translations.js")
else:
    print("Already in translations.js")

# And re-bump global cache strictly
with open('satis_faturasi.html', 'r', encoding='utf-8') as f:
    html = f.read()
import re
html = re.sub(r'translations\.js\?v=\d+', 'translations.js?v=601', html)
# Ensure the script tags are actually there as well.
if 'translations.js' not in html:
    html = html.replace('</body>', '\n<script src="translations.js?v=601"></script>\n<script src="script.js"></script>\n</body>')
with open('satis_faturasi.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Bumped satis_faturasi.html cache version to v=601")
